---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icproxy
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: icproxy-view
subjects:
- kind: ServiceAccount
  name: icproxy
roleRef:
  kind: Role
  name: view
---
apiVersion: v1
kind: Secret
metadata:
  name: router
  labels:
    application: myrouter
type: Opaque
stringData:
  connect.json: |-
    {
        "scheme": "amqp",
        "host": "messaging"
    }
---
